from .usuario import Usuario
from .rol import Rol
from .registro_usuario import RegistroUsuario
from .ingenieria import Ingenieria
from .estudiante import Estudiante
from .gestor import Gestor
from .admin import Admin
from .formulario_desercion import FormularioDesercion
from .pregunta import Pregunta
from .respuesta import Respuesta
from .curso import Curso
from .historial_academico import HistorialAcademico
from .corte_evaluacion import CorteEvaluacion
from .riesgo_socioeconomico import RiesgoSocioeconomico
from .desercion import Desercion
from .mensaje import Mensaje